--Для того щоб запустився цикл необхідно заповнити таблицю COUNTRY
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES ('UK');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES ('USA');
INSERT INTO COUNTRY(COUNTRY_NAME) VALUES ('UA');
